Fix build with prompts (#2)
* fix errors: declared and not used: schema, undefined: strings, undefined: time

* fix error: type distribution.NodeState has no field or method String

* remove unused imports

---------

Co-authored-by: Pratik Deshpande <pratikdeshpande@Pratiks-MacBook-Pro.local>
Co-authored-by: Pratik Deshpande <pratikdeshpande@pratiks-mbp.myfiosgateway.com>